version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/moul/grpcbin
    steps:
      - checkout
      - run: make download
      - run: make install
      - run: make test
      # - run: make integration
      #- run: make install-dev
      #- run: make lint
